- name: Install ssh tools
  become: true
  ansible.builtin.package:
    name:
      - xorg
      - xauth
      - openssh-client
      - openssh-server

- name: Add authorized keys
  become: true
  ansible.posix.authorized_key:
    user: "{{ ansible_env.USER }}"
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_items:
    - "{{ ssh_pub_files }}"

- name: Allow legacy ssh-rsa key encryption
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config.d/legacy_pubkey_types.conf"
    line: "PubkeyAcceptedKeyTypes +ssh-rsa"
    regexp: "^PubkeyAcceptedKeyTypes"
    insertafter: EOF
    create: true
    mode: "644"
  notify: RestartSshd
