- name: Install tmux tools
  become: true
  ansible.builtin.package:
    name:
      - tmux

- name: Add tmux config
  ansible.builtin.copy:
    src: .tmux.conf
    dest: "{{ ansible_env.HOME }}"
    mode: "u+rw"

- name: Ensure Unix line endings
  ansible.builtin.replace:
    path: "{{ ansible_env.HOME }}/.tmux.conf"
    regexp: "\r\n"
    replace: "\n" # noqa jinja[spacing]
