---

- name: Add intelliJ alias for all user profiles
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/profile.d/intellij.sh"
    line: "alias intellij='{{ ansible_local.intellij.general.home }}/bin/idea.sh &>/dev/null'"
    regexp: '^alias intellij='
    insertafter: EOF
    create: true
    mode: "o=rw,go=r"
