---

- name: create java installation directory
  become: yes
  file:
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
    dest: '/opt/java'

- name: set facts for openjdk version
  set_fact:
    jdk11_version: '11.0.11'
    jdk11_version_add: '9'

- name: 'download jdk-{{ jdk11_version }}+{{ jdk11_version_add }}'
  become: yes
  get_url:
    url: 'https://api.adoptopenjdk.net/v3/binary/version/jdk-{{ jdk11_version }}%2B{{ jdk11_version_add }}/linux/x64/jdk/hotspot/normal/adoptopenjdk?project=jdk'
    dest: '/opt/java/jdk-{{ jdk11_version }}.tar.gz'
    force: no
    use_proxy: yes
    validate_certs: yes
    mode: 'u=rw,go=r'

- name: install jdk 11
  become: yes
  unarchive:
    src: '/opt/java/jdk-{{ jdk11_version }}.tar.gz'
    remote_src: yes
    dest: '/opt/java'
    owner: root
    group: root
    mode: 'o-w'
    creates: '/opt/java/jdk-{{ jdk11_version }}+{{ jdk11_version_add }}/bin'

- name: set facts for openjdk locations
  set_fact:
    jdk11_home: '/opt/java/jdk-{{ jdk11_version }}+{{ jdk11_version_add }}'
