- name: Check if Ubuntu Desktop already installed
  ansible.builtin.command: dpkg-query -l ubuntu-desktop
  changed_when: false
  failed_when: false
  register: ubuntu_desktop

- name: Ensure no incompatible version of 'python3-software-properties' is installed
  become: true
  ansible.builtin.apt:
    name: python3-software-properties
    state: absent
  when: (ubuntu_desktop.rc == 1) and (wsl_is_wsl == false)

- name: Install Ubuntu Desktop
  become: true
  ansible.builtin.apt:
    name: ubuntu-desktop
  when: wsl_is_wsl == false

- name: Install Ubuntu Desktop missing dependencies (needed for vbox guest additions)
  become: true
  ansible.builtin.apt:
    name: linux-image-generic
  when: wsl_is_wsl == false

- name: Install psutil that is needed for dconf module below
  become: true
  ansible.builtin.apt:
    name: python3-psutil
  when: wsl_is_wsl == false

- name: Define all gnome favorite apps
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['org.gnome.Nautilus.desktop', 'firefox.desktop', 'org.gnome.Terminal.desktop', 'jetbrains-clion.desktop', 'jetbrains-idea-ce.desktop', 'code.desktop']"
  when: wsl_is_wsl == false

- name: Add german keyboard layouts
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'ch'), ('xkb', 'us')]"
  when: wsl_is_wsl == false
