- name: Download virtualbox additions ISO
  become: true
  ansible.builtin.package:
    name: virtualbox-guest-additions-iso
  when: not wsl_is_wsl

- name: Create virtualbox additions mount point
  become: true
  ansible.builtin.file:
    dest: /media/vbadd
    mode: "u+rw"
    state: directory
  when: not wsl_is_wsl

- name: Install virtualbox additions # noqa command-instead-of-module
  become: true
  ansible.builtin.shell: |
    mount /usr/share/virtualbox/VBoxGuestAdditions.iso /media/vbadd/
    /media/vbadd/VBoxLinuxAdditions.run --nox11
    umount /media/vbadd/
  args:
    creates: /usr/sbin/VBoxService
  when: not wsl_is_wsl

- name: Create group vboxsf
  become: true
  ansible.builtin.group:
    name: vboxsf
  when: not wsl_is_wsl

- name: Add user to vboxsf group to have access to bind mounts
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    append: true
    groups: vboxsf
  when: not wsl_is_wsl
