- name: Download virtualbox additions ISO
  become: true
  ansible.builtin.package:
    name: virtualbox-guest-additions-iso

- name: Create virtualbox additions mount point
  become: true
  ansible.builtin.file:
    dest: /media/vbadd
    state: directory

- name: Install virtualbox additions
  become: true
  ansible.builtin.shell: |
    mount /usr/share/virtualbox/VBoxGuestAdditions.iso /media/vbadd/
    /media/vbadd/VBoxLinuxAdditions.run --nox11
    umount /media/vbadd/
  args:
    creates: /usr/sbin/VBoxService

- name: Create group vboxsf
  become: true
  ansible.builtin.group:
    name: vboxsf

- name: Add user to vboxsf group to have access to bind mounts
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    append: true
    groups: vboxsf
