name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: macos-12
    env:
      VAGRANT_DISABLE_VBOXSYMLINKCREATE: "1"

    steps:
    - uses: actions/checkout@v2

    - name: Run vagrant up
      run: vagrant up
      working-directory: .github/workflows
